### ISSUE TITLE
kinopoisk.ru

### ISSUE THREAD

**Issue by madest92** [dimisa-RUAdList/RUAdListCDN#10]
I applied all filters to block ads starting with `www.kinopoisk.ru`

But when watching trailers, ads still appear

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/dimisa-RUAdList/RUAdListCDN/assets/22662307/04f3884d-b53d-4257-9bca-9d00a1845ccb)

</details>

**Comment by dimisa-RUAdList** [comment]
Оу, ветка CDN никогда не использовалась для рассмотрения проблем, и это не планируется в будущем. 

Если вы используете [поддерживаемую конфигурацию](https://forums.lanik.us/viewtopic.php?t=22512), то сообщить о возникающих проблемах вы можете либо на [официальном форуме RU AdList](https://forums.lanik.us/viewforum.php?f=102-ru-adlist), либо в основной ветке [RU AdList на гитхабе](https://github.com/easylist/ruadlist/issues).

При этом потребуется указать [все необходимые детали](https://forums.lanik.us/viewtopic.php?t=24280).
