### ISSUE TITLE
Can you add the github pages of the lists ?

### ISSUE THREAD

**Issue by DogancanYr** [dimisa-RUAdList/RUAdListCDN#12]
Because I realized that this was working as a merge and I had to go to the actual github pages to make corrections. May it be easier for those who come.

**Comment by dimisa-RUAdList** [comment]
All RU AdList filters are located here:
https://github.com/easylist/ruadlist

If you want to have access to them directly from the extension, you can write about it to its author: https://github.com/uBlockOrigin/uBlock-issues

**Comment by DogancanYr** [comment]
Can you write something like this at the top of the list?

This is the merge list, every 5-10 hours it is taken from the following lists
ru=https://github.com/easylist/ruadlist
ua=
uz=
kz=

**Comment by DogancanYr** [comment]
I wrote it, but didn't do it because didn't want to put a github link instead of a forum link.

**Comment by dimisa-RUAdList** [comment]
You are sending me questions that should be addressed to the author of the extension.

**Comment by DogancanYr** [comment]
Do you not have write permissions on this repository ?

**Comment by dimisa-RUAdList** [comment]
Your question does not concern the filter, but its representation in the extension. You can discuss the expansion or make suggestions for improvements here: https://github.com/uBlockOrigin/uBlock-issues

**Comment by DogancanYr** [comment]
I thought you could do it this way, but I'll try to explain it once again in the uBlock issues section.

```
[uBlock Origin 1.0]
! Title: RU AdList for uBO only
! Expires: 4 days
! Last modified: Sat, 27 Apr 2024 10:23:41 +0000
! This is the merge list, every 5-10 hours it is taken from the following lists
! ru=https://github.com/easylist/ruadlist
! ua=
! uz=
! kz=
! Diff-Path: ../patches/2024.4.27.623.patch#ruadlist
! Diff-Expires: 5 hours
! License: https://github.com/dimisa-RUAdList/RUAdListCDN/blob/main/LICENSE
! *** ruadlist:RuAdList-uBO.txt ***
! *** ./advblock/adservers.txt ***
```

**Comment by dimisa-RUAdList** [comment]
It is not clear to me why you want to see these addresses in the filter header.

**Comment by DogancanYr** [comment]
Where does Kazakhstan, Ukraine, Uzbekistan get its lists from?

**Comment by dimisa-RUAdList** [comment]
Please describe the problem completely. Why do you need this and what brought you to the idea of such a need?

**Comment by DogancanYr** [comment]
Let me start from the beginning, why is this repository taking from the other repository?

**Comment by dimisa-RUAdList** [comment]
Because that’s how the diff patching mechanism works. But this question does not explain in any way the reason why the idea of ​​creating the current issue arose. It will be easier if you really explain from the very beginning.

**Comment by DogancanYr** [comment]
There are only forum links from Ublock origins and the filter header doesn't say which github repository the file came from.

**Comment by dimisa-RUAdList** [comment]
Do you explain why you needed a repo address?

**Comment by DogancanYr** [comment]
To go to the repository url and make an edit suggestion.

**Comment by dimisa-RUAdList** [comment]
This method is an extremely unproductive path, very often forcing filter authors to engage in exhaustive messaging to obtain the necessary information about the configuration and relevance of the filters. Therefore, blockers usually use a “report a problem” button. In this case, all the necessary information is generated automatically. For uBlock Origin it is: https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website

**Comment by DogancanYr** [comment]
If I posted the previous problem, would it be fixed there quickly or would it take time?

**Comment by dimisa-RUAdList** [comment]
If you used the "report a problem" button, that would be the fastest way to resolve it.
